name: First Workflow

on:
  - push

jobs: 
  first_job: 
    name: My updated job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        
      - name: Updated Welcome Messagess
        run: echo "Welcome to the CICD world with Github Action"

      - name: List Files 
        run: ls

      - name: Display current worlking directory
        run: pwd
