name: First Workflow

on:
  - push

jobs: 
    first_job: 
        name: DevOps First Job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
            - name: List and Read files
              run: |
                echo "My first GitHub Actions Job"
                ls -la
                cat happy.txt
                
      
